// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operadoras.Persistence;
using Operadoras.Persistence.Contratos;
using Operadoras.Persistence.Contexto;

namespace Operadoras.Persistence.Migrations
{
    [DbContext(typeof(OperadorasContext))]
    [Migration("20220709185519_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Operadoras.Domain.Operadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeOperadora")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObsOperadora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operadoras");
                });

            modelBuilder.Entity("Operadoras.Domain.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumTelefone")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperadoraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperadoraId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("Operadoras.Domain.Telefone", b =>
                {
                    b.HasOne("Operadoras.Domain.Operadora", "Operadora")
                        .WithMany("NumTelefones")
                        .HasForeignKey("OperadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operadora");
                });

            modelBuilder.Entity("Operadoras.Domain.Operadora", b =>
                {
                    b.Navigation("NumTelefones");
                });
#pragma warning restore 612, 618
        }
    }
}
