// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operadoras.API.Data;

namespace Operadoras.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Operadoras.API.Models.Operadora", b =>
                {
                    b.Property<int>("OperadoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeOperadora")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumTelefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObsOperadora")
                        .HasColumnType("TEXT");

                    b.HasKey("OperadoraId");

                    b.ToTable("Operadoras");
                });
#pragma warning restore 612, 618
        }
    }
}
